### ISSUE TITLE
Website is more recent than github

### ISSUE THREAD

**Issue by larskanis** [oneclick/rubyinstaller.org#10]
Last change in this repository is on Nov. 2014 and there is no fork that matches to the running website.

@Azolo How did you update rubygems.org?

**Comment by Azolo** [comment]
> @Azolo How did you update rubygems.org?

I'm guessing you meant rubyinstaller.org. :wink:

This was an attempt at taking the CMS that backs the site now and turn it into a not CMS generated site. It never got that far.

**Comment by larskanis** [comment]
Of course rubyinstaller.org - sorry!

Provided that you agree with the switch to RubyInstaller2 for ruby-2.4, could I prepare the texts in the CMS? English is not my native language - insofar I would be glad if someone could review what I wrote. Do you have an idea how we can arrange this?
